nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3000'] # Allow only HTTP origin for your frontend
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': # Apply CORS to all API routes
            allow_origin: ['http://localhost:3000'] # Allow only HTTP origin
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
        '^/images/': # Allow access to the images folder
            allow_origin: ['http://localhost:3000']
            allow_methods: ['GET']
            allow_headers: ['Content-Type']